spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 1000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: groupId
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000

app:
  kafka:
    topic: meow
    producer:
      enable:
        idempotence: true
      max:
        in:
          flight:
            requests:
              per:
                connection: 5
                #spring.kafka.bootstrap-servers=localhost:9092
                #spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
                #spring.main.allow-bean-definition-overriding=true